### ISSUE TITLE
simplify client.ino code 

### ISSUE THREAD

**Issue by rootz491** [LucidMach/VOIT#1]
Try adding comments to code for **client.ino** file.
It will help understanding what exactly ESP module is doing!

**Comment by LucidMach** [comment]
yea, have to
It's going to be a drag
for now [HTTPClient Guide](https://randomnerdtutorials.com/esp8266-nodemcu-http-get-post-arduino/)

**Comment by LucidMach** [comment]
Mission Accomplished
Lemme Know if I could make the docs better

**Comment by rootz491** [comment]
looking good!
